version: '3.4'

services:
  lightbulb:
    image: lightbulb
    environment:
      - FLASK_APP=lightbulb
      - FLASK_ENV=development
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    volumes:
     - logs:/apps/logs/

volumes:
  logs: {}

